ALTER TABLE public.invoice_settings
    ADD COLUMN IF NOT EXISTS template_style VARCHAR(50) DEFAULT 'CLASSIC',
    ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) DEFAULT '#225378',
    ADD COLUMN IF NOT EXISTS font_family VARCHAR(50) DEFAULT 'HELVETICA',
    ADD COLUMN IF NOT EXISTS show_logo BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS tax_id_label VARCHAR(50) DEFAULT '',
    ADD COLUMN IF NOT EXISTS tax_id_value VARCHAR(100) DEFAULT '';
